# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.CharField(default='Padwan', max_length=50),
        ),
    ]
