# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 03:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_announcement_badge_statusreport'),
        ('payments', '0002_user_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnpaidUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, unique=True)),
                ('last_notification', models.DateTimeField(default=datetime.datetime(2017, 4, 10, 3, 54, 5, 153229))),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='badges',
            field=models.ManyToManyField(to='main.Badge'),
        ),
    ]
