# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20170410_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unpaidusers',
            name='last_notification',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
