# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 17:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
